env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceType: 'module'
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
  - airbnb
  - airbnb-typescript
  - next/core-web-vitals
rules:
  "import/prefer-default-export": "off"
  "react/function-component-definition": "off"
  "import/no-extraneous-dependencies": "off"
  "operator-linebreak": "off"